apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort        # <== 🔥 this is the key change
  selector:
    app: web
  ports:
    - port: 80          # service port
      targetPort: 80    # container port
      nodePort: 30080   # optional, choose from 30000-32767
